name: Run Alias Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'  # Adjust the Go version as needed

      - name: Run Alias tests
        run: go test -cover ./CSCE4600/Project2/builtins/alias_test.go
